// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerationAddin.Vsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidProjectCommandPackageString = "34ecf1f2-bfe8-4fa4-bec3-7c826900ae4c";
        public static Guid guidProjectCommandPackage = new Guid(guidProjectCommandPackageString);

        public const string guidProjectCommandPackageCmdSetString = "fbae26db-d45c-4922-839e-c0f655b10dbe";
        public static Guid guidProjectCommandPackageCmdSet = new Guid(guidProjectCommandPackageCmdSetString);

        public const string guidImagesString = "011b1bf8-43cd-4c25-9044-e1b6dc9982d3";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ProjectCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}