// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Electric.Navigation
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidNavigationPackageString = "0022995d-dbb7-45d2-8c38-243c4a429dc0";
        public static Guid guidNavigationPackage = new Guid(guidNavigationPackageString);

        public const string CmdSetString = "14e9d5e8-908c-4b9e-af00-1f0e78cc9c26";
        public static Guid CmdSet = new Guid(CmdSetString);

        public const string goldAqua_LightningString = "c3ab46b9-399c-4768-98fe-6d1c318bb923";
        public static Guid goldAqua_Lightning = new Guid(goldAqua_LightningString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolsMenuGroup = 0x1020;
        public const int FindSelectedCommand = 0x0101;
        public const int SearchToolWindowCommand = 0x0102;
        public const int command = 0x0001;
        public const int menu = 0x0002;
        public const int dialog = 0x0003;
        public const int dialogCircle = 0x0004;
        public const int dialogSquareDiamond = 0x0005;
        public const int circleToolWindow = 0x0006;
        public const int toolWindow = 0x0007;
    }
}