// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSAutomation
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSAutomationPackageString = "ca2c5815-341c-48d9-adf2-9a2863142717";
        public static Guid guidVSAutomationPackage = new Guid(guidVSAutomationPackageString);

        public const string CmdSetString = "52907988-07fb-4e2c-a1b1-ebcc504cb1f3";
        public static Guid CmdSet = new Guid(CmdSetString);

        public const string purpleRedLightningString = "c3ab46b9-399c-4768-98fe-6d1c318bb923";
        public static Guid purpleRedLightning = new Guid(purpleRedLightningString);

        public const string guidVSAutomationPackageCmdSetString = "ba70e522-da28-4b2d-a85d-12b4ab6b667e";
        public static Guid guidVSAutomationPackageCmdSet = new Guid(guidVSAutomationPackageCmdSetString);

        public const string guidImagesString = "81daabd9-ad8f-4289-b42f-4d94356c888c";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int VsAutomationGroup = 0x1020;
        public const int VsAutomationMenu = 0x1030;
        public const int VsAutomationMenuGroup = 0x1031;
        public const int SyncWithActiveDocumentId = 0x2002;
        public const int cmdidPersistSolutionOpenDocuments = 0x2000;
        public const int cmdidRestoreSolutionOpenDocuments = 0x2001;
        public const int cmdidAddBreakpointsToAllMethodsCommand = 0x0100;
        public const int cmdidRemoveBreakpointsFromDocument = 0x2003;
        public const int DocumentRightClickGroup = 0x3000;
        public const int purpleRedCommand = 0x0001;
        public const int purpleRedMenu = 0x0002;
        public const int purpleRedDialog = 0x0003;
        public const int purpleRedDialogCircle = 0x0004;
        public const int purpleRedDialogSquareDiamond = 0x0005;
        public const int purpleRedCircleToolWindow = 0x0006;
        public const int purpleRedToolWindow = 0x0007;
        public const int cmdidBreakPointToolWindowCommand = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}