// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerationAddin
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCodeGenerationAddinPackageString = "046fe648-3ce4-46f8-a00f-d24814f64689";
        public static Guid guidCodeGenerationAddinPackage = new Guid(guidCodeGenerationAddinPackageString);

        public const string guidCodeGenerationAddinPackageCmdSetString = "a0f22528-d604-4cc3-a294-5593f7bd7ffc";
        public static Guid guidCodeGenerationAddinPackageCmdSet = new Guid(guidCodeGenerationAddinPackageCmdSetString);

        public const string guidImagesString = "b6cf7619-986c-437e-98b6-cc30e30bbdfb";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ProjectMenuGroup = 0x1020;
        public const int ProjectCommandId = 0x0100;
        public const int CSharpMenuGroup = 0x1030;
        public const int CSharpCommandId = 0x0200;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}