// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Electric.History
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidHistoryPackageString = "d554680b-4922-4b6d-835b-cd8a32a5575b";
        public static Guid guidHistoryPackage = new Guid(guidHistoryPackageString);

        public const string CmdSetString = "d1b739ef-7229-4839-b150-389d74cd915b";
        public static Guid CmdSet = new Guid(CmdSetString);

        public const string guidImagesString = "73b877da-a11f-4cfa-a736-9afcc585266f";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolsMenuGroup = 0x0101;
        public const int SolutionHistoryToolWindowCommand = 0x0100;
        public const int command = 0x0001;
        public const int menu = 0x0002;
        public const int dialog = 0x0003;
        public const int dialogCircle = 0x0004;
        public const int dialogSquareDiamond = 0x0005;
        public const int circleToolWindow = 0x0006;
        public const int go_toolWindow = 0x0007;
    }
}