// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AttributeHelperAddin
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAttributeHelperAddinPackageString = "42236c3a-c547-4856-a628-21afb73601ba";
        public static Guid guidAttributeHelperAddinPackage = new Guid(guidAttributeHelperAddinPackageString);

        public const string guidAttributeHelperAddinPackageCmdSetString = "bea5802a-5f9a-4878-9162-4cf00cb14e1b";
        public static Guid guidAttributeHelperAddinPackageCmdSet = new Guid(guidAttributeHelperAddinPackageCmdSetString);

        public const string guidImagesString = "d2a76c89-9049-4ae1-a504-52ebda4f4416";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ApplyAttributeCommandId = 0x0100;
        public const int cmdidGetProjectItemLocationCommand = 0x1021;
        public const int command = 0x0001;
        public const int menu = 0x0002;
        public const int dialog = 0x0003;
        public const int dialogCircle = 0x0004;
        public const int dialogSquareDiamond = 0x0005;
        public const int circleToolWindow = 0x0006;
        public const int go_toolWindow = 0x0007;
    }
}