// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsGuiHelper
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVsGuiHelperPackageString = "1d3911df-d849-4851-ad50-85562f64eda7";
        public static Guid guidVsGuiHelperPackage = new Guid(guidVsGuiHelperPackageString);

        public const string guidVsGuiHelperPackageCmdSetString = "16e846ba-7a53-46dd-8575-36ab1fc82af7";
        public static Guid guidVsGuiHelperPackageCmdSet = new Guid(guidVsGuiHelperPackageCmdSetString);

        public const string guidImagesString = "7a2edef3-7791-4049-ac65-d763e8f3469a";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int SyncWithActiveDocumentId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}