// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Electric.Logging
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidLoggingPackageString = "f9efabbf-7152-449e-85a4-56ffd8507983";
        public static Guid guidLoggingPackage = new Guid(guidLoggingPackageString);

        public const string guidLoggingPackageCmdSetString = "858985a0-421c-4dfb-a7a3-3425398f8c77";
        public static Guid guidLoggingPackageCmdSet = new Guid(guidLoggingPackageCmdSetString);

        public const string guidImagesString = "38ba422f-38e7-4a14-8d3f-f9172d6f87c8";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int LoggingToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}