// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeAddIn
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCodeAddInPackageString = "0efaee20-08e5-4944-8ba7-a3eec5165f91";
        public static Guid guidCodeAddInPackage = new Guid(guidCodeAddInPackageString);

        public const string guidCodeAddInPackageCmdSetString = "66b2a8cf-1cdd-419e-8bff-11a781e955cf";
        public static Guid guidCodeAddInPackageCmdSet = new Guid(guidCodeAddInPackageCmdSetString);

        public const string guidImagesString = "395cfe74-ce19-4c9e-9496-ec99590fa6c0";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ProjectMenuGroup = 0x1020;
        public const int VsctMenuGroup = 0x0101;
        public const int CommandCsharpRoot = 0x0102;
        public const int CommandProjectRoot = 0x0103;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}