// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeAddIn
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCodeAddInPackageString = "0efaee20-08e5-4944-8ba7-a3eec5165f91";
        public static Guid guidCodeAddInPackage = new Guid(guidCodeAddInPackageString);

        public const string CmdSetString = "66b2a8cf-1cdd-419e-8bff-11a781e955cf";
        public static Guid CmdSet = new Guid(CmdSetString);

        public const string guidImagesString = "395cfe74-ce19-4c9e-9496-ec99590fa6c0";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidCodeAddInPackageCmdSetString = "34effc17-2057-42cb-899e-32db5af80e56";
        public static Guid guidCodeAddInPackageCmdSet = new Guid(guidCodeAddInPackageCmdSetString);

        public const string guidImages1String = "f11455bc-75cd-4f46-9038-69f6ad07ab7d";
        public static Guid guidImages1 = new Guid(guidImages1String);

        public const string guidImages2String = "76d1a8b3-e326-4028-a17c-67b53b2ef693";
        public static Guid guidImages2 = new Guid(guidImages2String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SolutionGroup = 0x1021;
        public const int CommandSolutionInfo = 0x0111;
        public const int SolutionMenu = 0x0106;
        public const int SolutionMenuGroup = 0x0107;
        public const int CommandInspectSolution = 0x0108;
        public const int CommandShowModified = 0x0109;
        public const int ProjectGroup = 0x1020;
        public const int ProjectInfoCommand = 0x0103;
        public const int ProjectMenu = 0x1112;
        public const int ProjectMenuGroup = 0x1113;
        public const int ProjectMenu1 = 0x1114;
        public const int CsharpInfoCommand = 0x0102;
        public const int VsctGroup = 0x0101;
        public const int VsctMenu = 0x1119;
        public const int VsctMenuGroup = 0x1118;
        public const int CommandVsctMenu1 = 0x1120;
        public const int CommandVsctMenu2 = 0x1122;
        public const int CommandSolutionRoot = 0x0105;
        public const int CommandVsctRoot = 0x0104;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int cmdidDirtyClassesToolWindowCommand = 0x0100;
        public const int cmdidToolWindow1Command = 0x0101;
    }
}